[package]
name = "rust-fizzbuzz"
version = "0.1.0"
authors = ["Jeff L. <jeff@langrsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
